# Generated by Django 4.1.4 on 2023-02-07 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('total_quantity', models.PositiveIntegerField(default=0.0)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0.0)),
                ('average_buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accumulated_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_profit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('symbol', 'user')},
            },
        ),
    ]
