# Generated by Django 4.1.4 on 2023-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='updated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
