# Generated by Django 4.1.4 on 2023-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatracker', '0002_stock_updated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='accumulated_spend',
            field=models.FloatField(default=0.0),
        ),
    ]
