# Generated by Django 4.1.4 on 2023-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatracker', '0003_alter_stock_accumulated_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='average_buy_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='profit_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_price',
            field=models.FloatField(default=0.0),
        ),
    ]
