# Generated by Django 4.1.4 on 2023-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatracker', '0004_alter_stock_average_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='profit_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
