# Generated by Django 4.1.4 on 2023-03-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatracker', '0005_stock_profit_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('last_price', models.FloatField(default=0.0)),
                ('price_yesterday', models.FloatField(default=0.0)),
                ('price_last_week', models.FloatField(default=0.0)),
                ('price_last_month', models.FloatField(default=0.0)),
                ('price_three_month', models.FloatField(default=0.0)),
                ('price_six_month', models.FloatField(default=0.0)),
            ],
        ),
    ]
